name: Package vsix

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure Git Agent
        run: |
          git config --global user.name 'Package Bot'
          git config --global user.email 'Package-bot@users.noreply.github.com'
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Use Node.js
        run: |
          npm install
          
      - name: Install vsce
        run: |
          npm install -g vsce

      - name: Package
        run: |
          vsce package
          
      - name: Commit file
        run: |
          git add code-annotation-0.0.2-dev.vsix
          git commit -nm "Updated vsix package"
          git push
